# Generated by Django 5.2.17 on 2026-09-30 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('manager_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('handled_by', models.ForeignKey(blank=True, db_column='handled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'db_table': 'feedbacks',
                'indexes': [models.Index(fields=['customer'], name='idx_feedbacks_customer'), models.Index(fields=['product'], name='idx_feedbacks_product'), models.Index(fields=['status'], name='idx_feedbacks_status'), models.Index(fields=['handled_by'], name='idx_feedbacks_handled_by'), models.Index(fields=['created_at'], name='idx_feedbacks_created_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='chk_feedbacks_rating')],
            },
        ),
    ]
