# Generated by Django 5.2.17 on 2026-09-30 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def align_mysql_schema(apps, schema_editor):
    """Keep the SQL contract while all business tables are still empty."""
    if schema_editor.connection.vendor != 'mysql':
        raise RuntimeError('The CRM schema requires MySQL')
    with schema_editor.connection.cursor() as cursor:
        # Django's generic DateTimeField/TextField use datetime(6)/longtext on MySQL.
        # The submitted SQL contract uses DATETIME/TEXT and database timestamp defaults.
        timestamps = {
            'accounts': [('last_login_at', 'DATETIME NULL'), ('created_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'), ('updated_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')],
            'customers': [('created_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'), ('updated_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), ('deleted_at', 'DATETIME NULL')],
            'categories': [('created_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'), ('updated_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')],
            'brands': [('created_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'), ('updated_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')],
            'suppliers': [('created_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'), ('updated_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')],
            'products': [('created_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'), ('updated_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')],
            'customer_preferences': [('created_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP')],
            'feedbacks': [('created_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'), ('resolved_at', 'DATETIME NULL')],
            'surveys': [('start_at', 'DATETIME NULL'), ('end_at', 'DATETIME NULL'), ('created_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'), ('updated_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')],
            'survey_recipients': [('sent_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'), ('opened_at', 'DATETIME NULL'), ('completed_at', 'DATETIME NULL')],
            'survey_responses': [('started_at', 'DATETIME NULL'), ('submitted_at', 'DATETIME NULL')],
            'survey_answers': [('created_at', 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP')],
        }
        for table, fields in timestamps.items():
            for column, definition in fields:
                cursor.execute(f'ALTER TABLE `{table}` MODIFY COLUMN `{column}` {definition}')
        text_fields = {
            'products': [('description', 'TEXT NULL')],
            'feedbacks': [('content', 'TEXT NOT NULL'), ('manager_note', 'TEXT NULL')],
            'surveys': [('description', 'TEXT NULL')],
            'survey_questions': [('question_text', 'TEXT NOT NULL')],
            'survey_answers': [('answer_text', 'TEXT NULL')],
        }
        for table, fields in text_fields.items():
            for column, definition in fields:
                cursor.execute(f'ALTER TABLE `{table}` MODIFY COLUMN `{column}` {definition}')
        for table, column, definition in (
            ('customers', 'status', "VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'"),
            ('categories', 'status', "VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'"),
            ('brands', 'status', "VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'"),
            ('suppliers', 'status', "VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'"),
            ('products', 'status', "VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'"),
            ('accounts', 'status', "VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'"),
            ('feedbacks', 'rating', 'TINYINT NOT NULL'),
            ('survey_answers', 'rating_value', 'TINYINT NULL'),
        ):
            cursor.execute(f'ALTER TABLE `{table}` MODIFY COLUMN `{column}` {definition}')

        # OneToOneField creates the right unique key with a generated name.
        cursor.execute('ALTER TABLE customers RENAME INDEX account_id TO uq_customers_account_id')
        checks = {
            'customers': [('chk_customers_status', "status IN ('ACTIVE', 'DELETED')")],
            'categories': [('chk_categories_status', "status IN ('ACTIVE', 'INACTIVE')")],
            'brands': [('chk_brands_status', "status IN ('ACTIVE', 'INACTIVE')")],
            'products': [('chk_products_price', 'price >= 0'), ('chk_products_status', "status IN ('ACTIVE', 'INACTIVE')")],
            'survey_questions': [('chk_survey_questions_sort_order', 'sort_order >= 0')],
            'survey_options': [('chk_survey_options_sort_order', 'sort_order >= 0')],
            'survey_answers': [('chk_survey_answers_rating', 'rating_value IS NULL OR rating_value BETWEEN 1 AND 5')],
        }
        for table, rules in checks.items():
            for name, condition in rules:
                cursor.execute(f'ALTER TABLE `{table}` ADD CONSTRAINT `{name}` CHECK ({condition})')

        indexes = {
            'customers': [('idx_customers_full_name', 'full_name'), ('idx_customers_phone', 'phone'), ('idx_customers_status', 'status')],
            'categories': [('idx_categories_name', 'category_name'), ('idx_categories_status', 'status')],
            'brands': [('idx_brands_name', 'brand_name'), ('idx_brands_status', 'status')],
            'products': [('idx_products_name', 'product_name'), ('idx_products_status', 'status'), ('idx_products_price', 'price')],
            'customer_preferences': [('idx_customer_preferences_customer', 'customer_id'), ('idx_customer_preferences_type', 'preference_type')],
            'surveys': [('idx_surveys_status', 'status'), ('idx_surveys_created_by', 'created_by'), ('idx_surveys_start_at', 'start_at'), ('idx_surveys_end_at', 'end_at')],
            'survey_questions': [('idx_survey_questions_type', 'question_type'), ('idx_survey_questions_sort', 'survey_id, sort_order')],
            'survey_options': [('idx_survey_options_sort', 'question_id, sort_order')],
            'survey_recipients': [('idx_survey_recipients_status', 'status')],
            'survey_responses': [('idx_survey_responses_status', 'status')],
        }
        for table, definitions in indexes.items():
            for name, fields in definitions:
                cursor.execute(f'CREATE INDEX `{name}` ON `{table}` ({fields})')

        foreign_keys = (
            ('customers', 'account_id', 'accounts', 'account_id', 'fk_customers_account', 'CASCADE', 'RESTRICT'),
            ('products', 'category_id', 'categories', 'category_id', 'fk_products_category', 'CASCADE', 'RESTRICT'),
            ('products', 'brand_id', 'brands', 'brand_id', 'fk_products_brand', 'CASCADE', 'RESTRICT'),
            ('products', 'supplier_id', 'suppliers', 'supplier_id', 'fk_products_supplier', 'CASCADE', 'RESTRICT'),
            ('customer_preferences', 'customer_id', 'customers', 'customer_id', 'fk_customer_preferences_customer', 'CASCADE', 'CASCADE'),
            ('feedbacks', 'customer_id', 'customers', 'customer_id', 'fk_feedbacks_customer', 'CASCADE', 'RESTRICT'),
            ('feedbacks', 'product_id', 'products', 'product_id', 'fk_feedbacks_product', 'CASCADE', 'RESTRICT'),
            ('feedbacks', 'handled_by', 'accounts', 'account_id', 'fk_feedbacks_handled_by', 'CASCADE', 'SET NULL'),
            ('surveys', 'created_by', 'accounts', 'account_id', 'fk_surveys_created_by', 'CASCADE', 'RESTRICT'),
            ('survey_questions', 'survey_id', 'surveys', 'survey_id', 'fk_survey_questions_survey', 'CASCADE', 'CASCADE'),
            ('survey_options', 'question_id', 'survey_questions', 'question_id', 'fk_survey_options_question', 'CASCADE', 'CASCADE'),
            ('survey_recipients', 'survey_id', 'surveys', 'survey_id', 'fk_survey_recipients_survey', 'CASCADE', 'CASCADE'),
            ('survey_recipients', 'customer_id', 'customers', 'customer_id', 'fk_survey_recipients_customer', 'CASCADE', 'RESTRICT'),
            ('survey_responses', 'recipient_id', 'survey_recipients', 'recipient_id', 'fk_survey_responses_recipient', 'CASCADE', 'CASCADE'),
            ('survey_answers', 'response_id', 'survey_responses', 'response_id', 'fk_survey_answers_response', 'CASCADE', 'CASCADE'),
            ('survey_answers', 'question_id', 'survey_questions', 'question_id', 'fk_survey_answers_question', 'CASCADE', 'CASCADE'),
            ('survey_answers', 'option_id', 'survey_options', 'option_id', 'fk_survey_answers_option', 'CASCADE', 'SET NULL'),
        )
        for table, column, target_table, target_column, name, update_rule, delete_rule in foreign_keys:
            cursor.execute(
                'SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE '
                'WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s '
                'AND REFERENCED_TABLE_NAME=%s', [table, column, target_table]
            )
            existing = cursor.fetchone()
            if existing is None:
                raise RuntimeError(f'Missing foreign key {table}.{column}')
            old_name = existing[0].replace('`', '``')
            cursor.execute(f'ALTER TABLE `{table}` DROP FOREIGN KEY `{old_name}`')
            cursor.execute(
                f'ALTER TABLE `{table}` ADD CONSTRAINT `{name}` FOREIGN KEY (`{column}`) '
                f'REFERENCES `{target_table}` (`{target_column}`) '
                f'ON UPDATE {update_rule} ON DELETE {delete_rule}'
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveys',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('survey', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
            options={
                'db_table': 'survey_questions',
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyquestion')),
            ],
            options={
                'db_table': 'survey_options',
            },
        ),
        migrations.CreateModel(
            name='SurveyRecipient',
            fields=[
                ('recipient_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('survey', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
            options={
                'db_table': 'survey_recipients',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.OneToOneField(db_column='recipient_id', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='surveys.surveyrecipient')),
            ],
            options={
                'db_table': 'survey_responses',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(blank=True, db_column='option_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.surveyoption')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyquestion')),
                ('response', models.ForeignKey(db_column='response_id', on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyresponse')),
            ],
            options={
                'db_table': 'survey_answers',
            },
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['survey'], name='idx_survey_questions_survey'),
        ),
        migrations.AddIndex(
            model_name='surveyoption',
            index=models.Index(fields=['question'], name='idx_survey_options_question'),
        ),
        migrations.AddIndex(
            model_name='surveyrecipient',
            index=models.Index(fields=['survey'], name='idx_survey_recipients_survey'),
        ),
        migrations.AddIndex(
            model_name='surveyrecipient',
            index=models.Index(fields=['customer'], name='idx_survey_recipients_customer'),
        ),
        migrations.AddConstraint(
            model_name='surveyrecipient',
            constraint=models.UniqueConstraint(fields=('survey', 'customer'), name='uq_survey_recipients_survey_customer'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('recipient',), name='uq_survey_responses_recipient'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['response'], name='idx_survey_answers_response'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['question'], name='idx_survey_answers_question'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['option'], name='idx_survey_answers_option'),
        ),
    ]
